### ISSUE TITLE
Installation fails due to ros-foxy-ur-msgs

### ISSUE THREAD

**Issue by robertokcanale** [UniversalRobots/Universal_Robots_ROS2_Driver#365]
I am trying to install the repo, following the turtorial steps.
But when I run:

_rosdep install --ignore-src --from-paths src -y -r_

I get the following error

executing command [sudo -H apt-get install -y ros-foxy-ur-msgs]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ros-foxy-ur-msgs
ERROR: the following rosdeps failed to install
  apt: command [sudo -H apt-get install -y ros-foxy-ur-msgs] failed
  apt: Failed to detect successful installation of [ros-foxy-ur-msgs]

How can I go forward?   I tired to go on with ros-foxy-ur-msgs but unfortunately there is no guide on how to install them as well.

Furthermore, If  I try to do colcon build i get the following:

Starting >>> ur_controllers
--- stderr: ur_controllers                          
CMake Error at CMakeLists.txt:29 (find_package):
  By not providing "Findur_msgs.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ur_msgs", but
  CMake did not find one.

  Could not find a package configuration file provided by "ur_msgs" with any
  of the following names:

    ur_msgsConfig.cmake
    ur_msgs-config.cmake

  Add the installation prefix of "ur_msgs" to CMAKE_PREFIX_PATH or set
  "ur_msgs_DIR" to a directory containing one of the above files.  If
  "ur_msgs" provides a separate development package or SDK, be sure it has
  been installed.

**Comment by destogl** [comment]
I think that `ur_msgs` package is released recently to foxy, so you need to call `rosdep update` to get the newest definitions. Or maybe the sync is still not out.

**Comment by fmauch** [comment]
Indeed there has not been a sync since we released the message package.

That's why the repo is still in the [Universal_Robots_ROS2_Driver-not-released.foxy.repos](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/foxy/Universal_Robots_ROS2_Driver-not-released.foxy.repos) file.

When building the driver as [explained in the README](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver#getting-started) things should work as expected.

@robertokcanale Did you follow any other instruction that has been missing the step of importingnon-released upstream repositories? If yes, which one? If not, please try following the instructions ;-)

**Comment by fmauch** [comment]
Since the driver ist released for Foxy by now I think this can be closed.
