### ISSUE TITLE
Should the default tool voltage be zero?

### ISSUE THREAD

**Issue by danzimmerman** [UniversalRobots/Universal_Robots_ROS2_Driver#521]
I'm digging into tool communication and realize that I plugged a gripper into the robot flange and ran the driver without really registering the idea that it could change the tool voltage from software, and that this voltage defaults to 24V:

https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/main/ur_robot_driver/launch/ur_control.launch.py#L533

This also applies to the robot description:

https://github.com/UniversalRobots/Universal_Robots_ROS2_Description/blob/ros2/urdf/ur.ros2_control.xacro#L16

I'm not even sure the `tool_voltage` parameter is active yet, maybe that's coming in with #466, and the **actual** tool voltage is still set to whatever it is inside Polyscope?

![image](https://user-images.githubusercontent.com/4365714/196824975-3a8bfaca-c6fc-4032-8b85-dafde68f29ba.png)

I suppose 12V tools are rare for power delivery reasons, and maybe have overvoltage protection anyway, but defaulting to zero and documenting that it needs to be configured might prevent some accidents for users with 12V tools.

**Comment by fmauch** [comment]
That is an absolutely valid point. It used to be set to 0 by default on the ROS1 driver, apparently this changed during the ROS2 migration. However, this seems to not get set due to missing https://github.com/UniversalRobots/Universal_Robots_Client_Library/pull/101.

I'll create a PR fixing both later today.
