### ISSUE TITLE
Add to the usage doc: how to control a UR robot via the moveit2 Cpp interface

### ISSUE THREAD

**Issue by FlorianPix** [UniversalRobots/Universal_Robots_ROS2_Driver#584]

**Comment by fmauch** [comment]
I'm sorry, but this is kind of out of scope for the driver, as this would be a MoveIt! tutorial. https://github.com/UniversalRobots/Universal_Robots_ROS_Tutorials might be a place for such a thing, but we currently don't plan to write that, so any contribution there would be welcome.

I'm going to close this here, since it is not a direct driver's issue.
