### ISSUE TITLE
hello_moveit project doesn't work

### ISSUE THREAD

**Issue by MuhammedErkam** [UniversalRobots/Universal_Robots_ROS2_Driver#665]
I am new at moveit. I am using this code -> https://moveit.picknik.ai/humble/doc/tutorials/your_first_project/your_first_project.html#plan-and-execute-using-movegroupinterface .  But I have this error below :

`[INFO] [1683541079.897863548] [moveit_rdf_loader.rdf_loader]: Robot model parameter not found! Did you remap 'robot_description'?

[FATAL] [1683541079.898045469] [move_group_interface]: Unable to construct robot model. Please make sure all needed information is on the parameter server.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unable to construct robot model. Please make sure all needed information is on the parameter server.
`
I dont know what to do. Could you help me?

**Comment by fmauch** [comment]
@MuhammedErkam This issue seems to have been overlooked, we are very sorry. Since  a lot of things have changed since then and you probably also spent some time in further investigations, I assume the problem does no longer exist in that form? Hence, I'll close this issue. Feel free to comment and reopen if the issue still persists.

In that case, please provide some version information, e.g. which ROS distribution you are using.
