### ISSUE TITLE
How to move ur robot by ros2 considering TCP  position

### ISSUE THREAD

**Issue by yinguoxiangyi** [UniversalRobots/Universal_Robots_ROS2_Driver#701]
I use following code to control ur robot. Also I set TCP position on the _Install_ tab of  robot TP . But the TCP position does not work : when I run the code , the flange always moves to the target, but not the TCP. How can I move the TCP to the target pose?
```
#include <memory>

#include <rclcpp/rclcpp.hpp>
#include <moveit/move_group_interface/move_group_interface.h>

int main(int argc, char * argv[])
{
  // Initialize ROS and create the Node
  rclcpp::init(argc, argv);
  auto const node = std::make_shared<rclcpp::Node>(
    "hello_moveit",
    rclcpp::NodeOptions().automatically_declare_parameters_from_overrides(true)
  );

  // Create a ROS logger
  auto const logger = rclcpp::get_logger("hello_moveit");

  // Next step goes here
  // Create the MoveIt MoveGroup Interface
  using moveit::planning_interface::MoveGroupInterface;
  auto move_group_interface = MoveGroupInterface(node, "ur_manipulator");
  move_group_interface.setPoseReferenceFrame("base");

  // Set a target Pose
  auto const target_pose = []{
    geometry_msgs::msg::Pose msg;
    msg.orientation.x = 0.0;
    msg.orientation.y = 0.0;
    msg.orientation.z = 0.0;
    msg.orientation.w = 1.0;
    msg.position.x = -0.2;
    msg.position.y = 0.1;
    msg.position.z = 0.8;
    return msg;
  }();
  std::vector<geometry_msgs::msg::Pose> waypoints;
  waypoints.push_back(target_pose);

  moveit_msgs::msg::RobotTrajectory trajectory;
  const double jump_threshold = 0.0;
  const double eef_step = 0.01;
  double fraction = move_group_interface.computeCartesianPath(waypoints, eef_step, jump_threshold, trajectory);
  RCLCPP_INFO(logger, "Visualizing plan 4 (Cartesian path) (%.2f%% achieved)", fraction * 100.0);

  // Execute the plan
  move_group_interface.execute(trajectory);
  // Shutdown ROS
  rclcpp::shutdown();
  return 0;
}
```

**Comment by fmauch** [comment]
In order to achieve what you want, you'll have to understand how things are playing together:

* This driver moves the robot around in joint space. the default `scaled_joint_trajectory_controller` takes trajectories in joint space and executes them.
* MoveIt! generates those joint trajectories based on a path planning from the robot's current pose to the target pose.
* As long as you don't change the TCP in MoveIt!, the planner will now know that you want to move a different place of your robot to your target pose.
* Changing the TCP on the Teach panel will not have any effect on this. It is merely an internal reference for the robot.

One way to achieve this would be to create your own MoveIt support package for your workcell setup (which you should be using, anyway) and define a custom end effector (and maybe planning group) for this. Then, you can move your robot using that custom end effector.

That being said, further explanations would go beyond the scope of this issue tracker, hence I'm going to close this. If you need further help setting up your workcell using MoveIt, I suggest going through the extensive  documentation or ask for help on ROS Answers.
