### ISSUE TITLE
IP Address not recognized: using driver with the Gazebo sim

### ISSUE THREAD

**Issue by tera-bytes** [UniversalRobots/Universal_Robots_ROS2_Driver#926]
Hi,

I'm working on Humble and using the Gazebo simulation from the other repo for the ur5e. When I try to launch the ur_robot_driver with my machine's ip address, it fails to connect to robot with that ip address. Is there something specific we need to use for the Gazebo simulation?

**Comment by RobertWilbrandt** [comment]
Please take a look at the [Universal_Robots_ROS2_Gazebo_Simulation](https://github.com/UniversalRobots/Universal_Robots_ROS2_Gazebo_Simulation) README, it describes what you have to start in order to be able to simulate a robot in the [Running Simulation](https://github.com/UniversalRobots/Universal_Robots_ROS2_Gazebo_Simulation?tab=readme-ov-file#running-simulation) section. In short: For the simulated case you don't need to start this driver, you only need to start the gazebo launch files:
```
ros2 launch ur_simulation_gazebo ur_sim_control.launch.py
```

Please let us know if you have further questions or problems with this.
